removed mypy totally

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,7 +17,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          pip install ruff mypy pydocstyle pytest
+          pip install ruff pydocstyle pytest
       
       - name: Install package in development mode
         run: pip install -e .
@@ -29,4 +29,4 @@ jobs:
      # - name: Mypy type check
      #   run: mypy . --install-types --non-interactive
       - name: Pydocstyle
-        run: pydocstyle . || true  # don't fail build on docstyle at start
+        run: pydocstyle . || true  # Allow pydocstyle to fail without failing the job
